markdown: rdiscount
permalink: /:title
title: Meroa
production_url : http://meroa.github.com
url : http://meroa.github.com
exclude: [ README.md ]
email: zhuwx@mail.ustc.edu.cn
domain: meroa.github.com
auto: true
googleAnalyticsID: UA-593131-4
disqusShortname: zhuwenxiang
