markdown: rdiscount
permalink: /:title
title: Meroa
url: http://meroa.com
subscribe: http://meroa.com/feed.xml
exclude: [ README.md ]
domain: meroa.com
email: zhuwenxiang@gmail.com
auto: true
googleAnalyticsID: UA-593131-4
disqusShortname: zhuwenxiang
